### ISSUE TITLE
Feature req.: DOSBox-X support?

### ISSUE THREAD

**Issue by hiatsu0** [rtts/ialauncher#13]
I only recently discovered the awesome fork of original DOSBox, called DOSBox-x (https://github.com/joncampbell123/dosbox-x) which seems to work way better on macOS and comes with lots of improvements. 

Any chance ialauncher could be mapped to launch `dosbox-x` instead of `dosbox`? Perhaps a selection/options screen, shown on first run, where user could select from a list of discovered dosbox* installations, or point to their own custom install path manually?

**Comment by JaapJoris** [comment]
Thanks for the feedback, and that seems like a really nice project! The easiest way to use DOSBox-X with IA Launcher would be to alias the `dosbox` command. Put the following in `~/.profile`

    alias dosbox=dosbox-x

The first place where IA Launcher looks when starting DOSBox is the `dosbox` command. If that is not available, it searches for some common installation locations for the original DOSBox. If you would like to use another program, just make sure you can start it by typing `dosbox` in your terminal. It could even be a shell script.

Hopefully these instructions were helpful. Feel free to reopen this issue if you run into any trouble.
