### ISSUE TITLE
Some notes on installation on Fedora

### ISSUE THREAD

**Issue by faassen** [rtts/ialauncher#3]
On Fedora 31 I had to do the following to get things working, perhaps useful for the documentation (I already had python3, but I think you need python3-devel):

`dnf install python3-devel dosbox webkit2gtk2-devel gobject-introspection-devel`

**Comment by JaapJoris** [comment]
The latest version is no longer based on Webkit, so there is no more need to install any external dependencies (besides DOSBox, of course). Installation is now as simple as a single `pip install ialauncher`!
