### ISSUE TITLE
Installation fails on macOS 11.1 (M1)

### ISSUE THREAD

**Issue by hiatsu0** [rtts/ialauncher#6]
Below is the error I get when trying to install on a fresh Big Sur, no Homebrew or anything installed. Some Xcode related stuff was installed the first time I attempted the installation. Seems to point to pygame issue? Is Homebrew required?

    username@macbook ~ % sudo pip3 install ialauncher    
    WARNING: The directory '/Users/username/Library/Caches/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
    Collecting ialauncher
      Downloading ialauncher-2.1.0.tar.gz (49.9 MB)
         |████████████████████████████████| 49.9 MB 6.5 MB/s 
    Collecting pygame
      Downloading pygame-2.0.1.tar.gz (5.5 MB)
         |████████████████████████████████| 5.5 MB 5.0 MB/s 
        ERROR: Command errored out with exit status 1:
         command: /Library/Developer/CommandLineTools/usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-y7l_yf6z/pygame_d4b473950bce48ccb4e4c7a8519f6fd3/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-y7l_yf6z/pygame_d4b473950bce48ccb4e4c7a8519f6fd3/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/tmp/pip-pip-egg-info-im41avie
             cwd: /private/tmp/pip-install-y7l_yf6z/pygame_d4b473950bce48ccb4e4c7a8519f6fd3/
        Complete output (27 lines):
    
    
    WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
    Using Darwin configuration...
    
    /bin/sh: sdl2-config: command not found
    /bin/sh: sdl2-config: command not found
    /bin/sh: sdl2-config: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-install-y7l_yf6z/pygame_d4b473950bce48ccb4e4c7a8519f6fd3/setup.py", line 318, in <module>
        buildconfig.config.main(AUTO_CONFIG)
      File "/private/tmp/pip-install-y7l_yf6z/pygame_d4b473950bce48ccb4e4c7a8519f6fd3/buildconfig/config.py", line 221, in main
        deps = CFG.main(**kwds)
      File "/private/tmp/pip-install-y7l_yf6z/pygame_d4b473950bce48ccb4e4c7a8519f6fd3/buildconfig/config_darwin.py", line 131, in main
        [DependencyProg('SDL', 'SDL_CONFIG', 'sdl2-config', '2.0', ['sdl'])],
      File "/private/tmp/pip-install-y7l_yf6z/pygame_d4b473950bce48ccb4e4c7a8519f6fd3/buildconfig/config_unix.py", line 39, in __init__
        self.ver = config[0].strip()
    IndexError: list index out of range
    
    ---
    For help with compilation see:
        https://www.pygame.org/wiki/MacCompile
    To contribute to pygame development see:
        https://www.pygame.org/contribute.html
    ---
    
    ----------------------------------------
    ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    username@macbook ~ %

**Comment by JaapJoris** [comment]
From your output it seems that `pip` tried to compile pygame and failed. It shouldn't even try, because pygame offers pre-compiled binaries as wheels. Maybe you are not supposed to use `sudo`?

Could you try running the following commands (without `sudo`) and post the output?

    $ pip3 install wheel
    $ pip3 install pygame
    $ pip3 install ialauncher

**Comment by hiatsu0** [comment]
Here you go. `Wheel` seems to be already there. Could it be that precompiled binaries are not available yet as this is an Apple Silicon mac? I think I'll try run `Terminal` with `Rosetta2` next..
    
    username@macbook ~ % python3
    Python 3.8.2 (default, Nov  4 2020, 21:23:28) 
    [Clang 12.0.0 (clang-1200.0.32.28)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> ^D
    
    username@macbook ~ % pip3 install wheel
    Defaulting to user installation because normal site-packages is not writeable
    Requirement already satisfied: wheel in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages (0.33.1)
    
    username@macbook ~ % pip3 install pygame
    Defaulting to user installation because normal site-packages is not writeable
    Collecting pygame
      Using cached pygame-2.0.1.tar.gz (5.5 MB)
        ERROR: Command errored out with exit status 1:
         command: /Library/Developer/CommandLineTools/usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/4p/x25zqqtd5mb8c3g2r1cq1w600000gn/T/pip-install-c7tsi00v/pygame_b8f4579f0b0f404ca80c5d587e5755d7/setup.py'"'"'; __file__='"'"'/private/var/folders/4p/x25zqqtd5mb8c3g2r1cq1w600000gn/T/pip-install-c7tsi00v/pygame_b8f4579f0b0f404ca80c5d587e5755d7/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/4p/x25zqqtd5mb8c3g2r1cq1w600000gn/T/pip-pip-egg-info-lavgh6zc
             cwd: /private/var/folders/4p/x25zqqtd5mb8c3g2r1cq1w600000gn/T/pip-install-c7tsi00v/pygame_b8f4579f0b0f404ca80c5d587e5755d7/
        Complete output (27 lines):
        
        
    WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
    Using Darwin configuration...
    
    /bin/sh: sdl2-config: command not found
    /bin/sh: sdl2-config: command not found
    /bin/sh: sdl2-config: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/4p/x25zqqtd5mb8c3g2r1cq1w600000gn/T/pip-install-c7tsi00v/pygame_b8f4579f0b0f404ca80c5d587e5755d7/setup.py", line 318, in <module>
        buildconfig.config.main(AUTO_CONFIG)
      File "/private/var/folders/4p/x25zqqtd5mb8c3g2r1cq1w600000gn/T/pip-install-c7tsi00v/pygame_b8f4579f0b0f404ca80c5d587e5755d7/buildconfig/config.py", line 221, in main
        deps = CFG.main(**kwds)
      File "/private/var/folders/4p/x25zqqtd5mb8c3g2r1cq1w600000gn/T/pip-install-c7tsi00v/pygame_b8f4579f0b0f404ca80c5d587e5755d7/buildconfig/config_darwin.py", line 131, in main
        [DependencyProg('SDL', 'SDL_CONFIG', 'sdl2-config', '2.0', ['sdl'])],
      File "/private/var/folders/4p/x25zqqtd5mb8c3g2r1cq1w600000gn/T/pip-install-c7tsi00v/pygame_b8f4579f0b0f404ca80c5d587e5755d7/buildconfig/config_unix.py", line 39, in __init__
        self.ver = config[0].strip()
    IndexError: list index out of range
    
    ---
    For help with compilation see:
        https://www.pygame.org/wiki/MacCompile
    To contribute to pygame development see:
        https://www.pygame.org/contribute.html
    ---
    
    ----------------------------------------
    ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    username@macbook ~ %

**Comment by hiatsu0** [comment]
Running the `Terminal` with `Rosetta2` seemed to fix this:

    username@macbook~ % sudo pip3 install ialauncher
    Password:
    WARNING: The directory '/Users/username/Library/Caches/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
    Collecting ialauncher
      Downloading ialauncher-2.1.0.tar.gz (49.9 MB)
         |████████████████████████████████| 49.9 MB 6.0 MB/s 
    Collecting pygame
      Downloading pygame-2.0.1-cp38-cp38-macosx_10_9_intel.whl (6.9 MB)
         |████████████████████████████████| 6.9 MB 13.1 MB/s 
    Building wheels for collected packages: ialauncher
      Building wheel for ialauncher (setup.py) ... done
      Created wheel for ialauncher: filename=ialauncher-2.1.0-py3-none-any.whl size=50979732 sha256=df067d2c22432d80967fb2fc85f3c2b04cd68dbcabdbc3bcd8de32fb2cfd6569
      Stored in directory: /private/tmp/pip-ephem-wheel-cache-efavhw3j/wheels/f7/55/99/96eae9ec3448f62bcf1a5ad4fcbebda0c785fabb723242dfa7
    Successfully built ialauncher
    Installing collected packages: pygame, ialauncher
    Successfully installed ialauncher-2.1.0 pygame-2.0.1
