### ISSUE TITLE
Unable to locate DOSBox.app on macOS 11.1

### ISSUE THREAD

**Issue by hiatsu0** [rtts/ialauncher#7]
IA Launcher seems to be unable to locate `DOSBox`, even if it is available in Applications. Is there any option to point it?
As this is an M1 Mac, the `terminal.app` (and `DOSBox.app` alone as well) are being run in `Rosetta2` mode.

(Also, should `ialauncher` become visible in Applications folder after installation, or is it always intended to be run from terminal only?)

    username@macbook ~ % ialauncher
    pygame 2.0.1 (SDL 2.0.14, Python 3.8.2)
    Hello from the pygame community. https://www.pygame.org/contribute.html
    
    Uh-oh! The program DOSBox could not be found on your system.
    IA Launcher acts as a frontend for DOSBox: when you select a game,
    it starts DOSBox with the right arguments to play that game.
    
    Please visit https://www.dosbox.com/ to learn more about DOSBox and
    download the correct installer for your operating system.
    
    Press any key to exit...
        
    username@macbook MacOS % /Applications/dosbox.app/Contents/MacOS/DOSBox 
    DOSBox version 0.74-3-3
    Copyright 2002-2019 DOSBox Team, published under GNU GPL.
    ---
    CONFIG:Loading primary settings from config file /Users/username/Library/Preferences/DOSBox 0.74-3-3 Preferences
    Unable to obtain graphics context for NSWindow (Mojave behavior)
    Unable to obtain graphics context for NSWindow (Mojave behavior)
    MIDI:Opened device:coreaudio

**Comment by JaapJoris** [comment]
IA Launcher tests if DOSBox is available by running the following command:

    $ dosbox --version

Could you verify this command returns successfully on your system?

**Comment by hiatsu0** [comment]
The command `dosbox` does not seem to be recognized at all:

    username@macbook ~ % dosbox --version
    zsh: command not found: dosbox

Interestingly, using `open -a DOSBox` seems to work launching DOSBox from Terminal.

**Comment by JaapJoris** [comment]
It should now be fixed in the latest version 2.1.2. Use the command `pip3 install --upgrade ialauncher` to install it.
