### ISSUE TITLE
Windows installer (2.1.0) does not work with Windows 7

### ISSUE THREAD

**Issue by anzz1** [rtts/ialauncher#8]
Windows installer (2.1.0) does not work with Windows 7 because it is compiled with Python 3.9 which does not support Windows 7 anymore. Compiling the installer with Python 3.8 should fix the issue.

**Comment by JaapJoris** [comment]
I know this doesn't sound very retro of me, but I do not want to support ancient operating systems like Windows 7. You can still get it running yourself by installing Python 3.8 manually and running `pip3 install ialauncher`. Feel free to open a new issue if that doesn't work!

**Comment by anzz1** [comment]
If someone else has the same problem you can also install ialauncher normally, then replace the Python3.9 DLLs in the ialauncher directory with ones from the [Python W7 compatibility fork](https://github.com/NulAsh/cpython)

I packed just the DLLs from the python package for your convenience. These match the 2.1.1 version of IALauncher (Python version 3.9.1150.1013)
[python3.9.1_w7_DLLs.zip](https://github.com/rtts/ialauncher/files/8384982/python3.9.1_w7_DLLs.zip)
